# Generated by Django 5.1.4 on 2024-12-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Family', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=30)),
            ],
        ),
    ]
